# Toledo/Scampart cleanup: removes leftover original .jpg files
# that were already converted to .webp and are no longer used by the live site.
# Only deletes the exact 208 filenames listed below - nothing else is touched.

$ErrorActionPreference = "Stop"
$imagesFolder = Join-Path $PSScriptRoot "images"

if (-not (Test-Path $imagesFolder)) {
    Write-Host "Could not find an 'images' folder next to this script." -ForegroundColor Red
    Write-Host "Place this script directly in your scampart-website repo folder and run it again."
    Read-Host "Press Enter to exit"
    exit 1
}

$filesToDelete = @(
    "airplane-heart-clouds.jpg",
    "album-cover-devil.jpg",
    "anim-animated-logo-sting.jpg",
    "anim-broccoli-walk-on.jpg",
    "anim-dashboard-walkthrough-explainer.jpg",
    "anim-lego-pilot-scene.jpg",
    "anim-line-art-day-in-the-life.jpg",
    "anim-obic-animation.jpg",
    "anim-presenter-character-explainer.jpg",
    "anim-tightrope-balance-explainer.jpg",
    "anim-trainer-character-explainer.jpg",
    "career-timeline-comic.jpg",
    "cd-bow-tie-character.jpg",
    "cd-broccoli-sheet.jpg",
    "cd-hat-character-rig.jpg",
    "cd-office-background.jpg",
    "cd-party-foul-game.jpg",
    "cd-party-scene.jpg",
    "cd-self-caricature-rig.jpg",
    "cd-turtle-turnaround.jpg",
    "cd-water-cooler.jpg",
    "celeb-argyle-mustache.jpg",
    "celeb-basketball-neon.jpg",
    "celeb-bernie-sanders.jpg",
    "celeb-bow-tie-statesman.jpg",
    "celeb-bubbles.jpg",
    "celeb-caped-crusader.jpg",
    "celeb-damask-actor.jpg",
    "celeb-danny-devito.jpg",
    "celeb-deadpool-wolverine.jpg",
    "celeb-deadwood.jpg",
    "celeb-desert-scavenger.jpg",
    "celeb-drill-sergeant.jpg",
    "celeb-eastbound-down.jpg",
    "celeb-firefist.jpg",
    "celeb-gunslinger-poncho.jpg",
    "celeb-hitman-poster.jpg",
    "celeb-jay-z.jpg",
    "celeb-jelly-roll.jpg",
    "celeb-johnny-cash.jpg",
    "celeb-knife-throw.jpg",
    "celeb-leonard-nimoy.jpg",
    "celeb-mission-impossible.jpg",
    "celeb-morgan-freeman.jpg",
    "celeb-music-trio.jpg",
    "celeb-paulie-walnuts.jpg",
    "celeb-phil-collins.jpg",
    "celeb-pulp-fiction.jpg",
    "celeb-rick-ross.jpg",
    "celeb-robin-williams.jpg",
    "celeb-ron-howard.jpg",
    "celeb-self-side-profile.jpg",
    "celeb-thanos.jpg",
    "celeb-the-jerk.jpg",
    "celeb-the-pope.jpg",
    "celeb-wide-brim-gambler.jpg",
    "celeb-zz-top.jpg",
    "challenge-interface.jpg",
    "change-management-scene.jpg",
    "character-guided-scenario.jpg",
    "claddagh-crest.jpg",
    "coach-character-scene.jpg",
    "comm-avengers-family.jpg",
    "comm-bobblehead-crate.jpg",
    "comm-cartoon-basketball.jpg",
    "comm-construction-quality-control.jpg",
    "comm-dragon-boat-team.jpg",
    "comm-explorer-luggage.jpg",
    "comm-firefighter.jpg",
    "comm-framed-portraits.jpg",
    "comm-frequent-flyer.jpg",
    "comm-golfer.jpg",
    "comm-lakeside-cats.jpg",
    "comm-line-art-couple.jpg",
    "comm-mustang-road-trip.jpg",
    "comm-pizza-cook.jpg",
    "comm-retirement-truck.jpg",
    "comm-retro-cartoon-villain.jpg",
    "comm-retro-gamer.jpg",
    "comm-shirt-rip-hero.jpg",
    "comm-superhero-comic-cover.jpg",
    "comm-wedding-couple.jpg",
    "company-overview-screen.jpg",
    "course-map-interface.jpg",
    "drum-mascot-congrats.jpg",
    "energy-drink-icons.jpg",
    "equipment-dealer-spot-art.jpg",
    "fire-comic-strip.jpg",
    "game-learning-splash.jpg",
    "giant-lizard-city.jpg",
    "heart-in-hands.jpg",
    "hero.jpg",
    "hipster-car-burger.jpg",
    "holiday-card-caricatures.jpg",
    "hospitality-infographics.jpg",
    "ill-bear-and-monsters.jpg",
    "ill-bear-in-track-pants.jpg",
    "ill-beast-man.jpg",
    "ill-brain-in-a-jar.jpg",
    "ill-chewbacca.jpg",
    "ill-clownhunter.jpg",
    "ill-cocktail-hour-tv.jpg",
    "ill-dark-knight.jpg",
    "ill-deadpool-cable.jpg",
    "ill-eyeball-tangle.jpg",
    "ill-glowing-guardian.jpg",
    "ill-golden-retriever.jpg",
    "ill-happy-pineapple.jpg",
    "ill-hazmat-suit.jpg",
    "ill-he-man-villains.jpg",
    "ill-hooked-goldfish.jpg",
    "ill-horned-robe.jpg",
    "ill-jason.jpg",
    "ill-kingpin.jpg",
    "ill-lab-background.jpg",
    "ill-lava-reaper.jpg",
    "ill-merman.jpg",
    "ill-monster-tangle.jpg",
    "ill-mosquito-man.jpg",
    "ill-mr-freeze.jpg",
    "ill-officer-freeze.jpg",
    "ill-orko.jpg",
    "ill-pancake-monster.jpg",
    "ill-panicked-chicken.jpg",
    "ill-red-demon-hero.jpg",
    "ill-red-elephant.jpg",
    "ill-robot-heart-balloon.jpg",
    "ill-scooter-rider.jpg",
    "ill-skater-devil.jpg",
    "ill-skeletor.jpg",
    "ill-skull-pop.jpg",
    "ill-splash-zone.jpg",
    "ill-steamboat-kids.jpg",
    "ill-sunset-gharial.jpg",
    "ill-swamp-xenomorph.jpg",
    "ill-tangled-totem.jpg",
    "ill-tentacle-summoner.jpg",
    "ill-tiki-scream.jpg",
    "ill-tusked-shark.jpg",
    "ill-tv-head-roach.jpg",
    "ill-two-monsters.jpg",
    "ill-witch-doctor-cauldron.jpg",
    "ill-yellow-brick-road.jpg",
    "ill-yoda.jpg",
    "ill-zombie-number-13.jpg",
    "maumee-valley-movers.jpg",
    "metro-navigation.jpg",
    "our-story-classroom.jpg",
    "pirate-ship-scene.jpg",
    "pp-betta-fish.jpg",
    "pp-birch-trees-in-snow.jpg",
    "pp-chameleon.jpg",
    "pp-chimpanzee.jpg",
    "pp-crested-bird.jpg",
    "pp-goldfish.jpg",
    "pp-kingfisher.jpg",
    "pp-octopus.jpg",
    "pp-owl-in-flight.jpg",
    "pp-parrot-portrait.jpg",
    "pp-red-eyed-tree-frog.jpg",
    "pp-robin-on-a-branch.jpg",
    "pp-tiki-guardian.jpg",
    "pp-tin-man-balloon.jpg",
    "recipe-for-success-scene.jpg",
    "recognition-program-collage.jpg",
    "reel-poster.jpg",
    "rudys-hot-dog-king.jpg",
    "safety-game-screen.jpg",
    "sb-airport-lounge.jpg",
    "sb-bar-scene.jpg",
    "sb-bowling-alley.jpg",
    "sb-cubicle-aisle.jpg",
    "sb-equipment-rental.jpg",
    "sb-five-expectations.jpg",
    "sb-grocery-clerk.jpg",
    "sb-grocery-story.jpg",
    "sb-growth-stages.jpg",
    "sb-meeting-room-32.jpg",
    "sb-office-chase.jpg",
    "sb-route-meeting.jpg",
    "sk-anteater.jpg",
    "sk-braided-caricature-sketch.jpg",
    "sk-bulldog.jpg",
    "sk-burnt-match.jpg",
    "sk-character-sketch-page.jpg",
    "sk-chewbacca-and-c-3po.jpg",
    "sk-creature-from-the-black-lagoon.jpg",
    "sk-dachshund.jpg",
    "sk-egg-tragedy.jpg",
    "sk-godzilla-on-wheels.jpg",
    "sk-jack-in-the-box.jpg",
    "sk-marker-monsters.jpg",
    "sk-night-diver.jpg",
    "sk-party-shark.jpg",
    "sk-pennywise.jpg",
    "sk-piranha-plant.jpg",
    "sk-raid-bug.jpg",
    "sk-sphynx-cat.jpg",
    "sk-teeny-little-super-guy.jpg",
    "sk-tin-man-under-the-moon.jpg",
    "sk-waldo.jpg",
    "sk-wandering-mouse.jpg",
    "spirit-songbook.jpg",
    "stretched-athlete-caricature.jpg",
    "teddy-bear-building.jpg",
    "training-storyboard-green.jpg",
    "traveler-window-seat.jpg",
    "workshop-experience.jpg"
)

$deleted = 0
$missing = 0
$freedBytes = 0

foreach ($name in $filesToDelete) {
    $path = Join-Path $imagesFolder $name
    if (Test-Path $path) {
        $freedBytes += (Get-Item $path).Length
        Remove-Item $path -Force
        $deleted++
    } else {
        $missing++
    }
}

$freedMB = [math]::Round($freedBytes / 1MB, 1)
Write-Host ""
Write-Host "Done." -ForegroundColor Green
Write-Host "Deleted: $deleted files ($freedMB MB freed)"
if ($missing -gt 0) {
    Write-Host "Already missing (skipped): $missing files"
}
Read-Host "Press Enter to exit"
